---
title: "EDA HDV"
output:
  word_document: default
  html_document: default
date: "2025-11-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tinytex)
library(rmarkdown)
library(arsenal)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(kableExtra)
library(GGally)
library(ggpubr)
library(ggrepel)
library(dslabs)
library(corrplot)
library(ggExtra)
library(car)
library(plotly)
#library(rgl)
library(scatterplot3d)

```


```{r}
setwd("~/Documents/GW Time/Fall 2025/Linear Reg/")
```


```{r}
load("~/Documents/GW Time/Fall 2025/Linear Reg/hypoxia.Rdata")
head(hypoxia)



hypoxia <- hypoxia[hypoxia$`Type Surg` != 4,]
hypoxia <- hypoxia[hypoxia$BMI != 23.4,]
```




```{r}
# make a default theme for the boxplots 
bxplt_theme <-    theme_minimal(base_size = 14)+ theme(
      plot.title = element_text(hjust = 0.5, face = "bold", size = 18),  # Centered, bold title    
      axis.text = element_text(size = 12, color = "black"),
      legend.position = "none",
      strip.background = element_rect(fill = "gray90", color = "black"),
      strip.text = element_text(size = 12, face = "bold"),
      panel.grid.major = element_line(color = "gray80", linetype = "dashed"), 
      panel.grid.minor = element_blank()
    ) 

# make a default theme for the barplots
brplt_theme <- theme_minimal(base_size = 14) +theme(
      plot.title = element_text(hjust = 0.5, face = "bold", size = 18),  # Centered, bold title    
      axis.text = element_text(size = 12, color = "black"),
      legend.position = "top",
      panel.grid.major = element_line(color = "gray80", linetype = "dashed"), 
      panel.grid.minor = element_blank()
)
```


```{r}
# contingency table for type of surgery
type_counts <- xtabs(~ `Type Surg` , data = hypoxia)

# reshape into long format where we see which diseases are present at each type of surgery
outcome_counts <- hypoxia %>%   
  dplyr::select(`Type Surg`, Smoking, Diabetes, Hyper, CAD) %>%  
  gather(key = "Condition", value = "Diagnosis", -c(`Type Surg`))  %>%
  filter(Diagnosis == 1)

com_counts <- outcome_counts %>%  
group_by(Condition, `Type Surg`) %>%
  count(`Type Surg`, Condition)
com_counts
```

```{r}


com_props <- com_counts %>%  
group_by(Condition, `Type Surg`) %>%  
group_by(`Condition`) %>%  
mutate(Proportion = n / sum(n))

com_props$`Type Surg` <- as.factor(com_props$`Type Surg`)

png("finalfig1.png", width = 1920, height = 1080, res = 300)

ggplot(com_props, aes(fill=Condition, x=`Type Surg`, y = Proportion)) + # might be better with stacked barplot? 
  geom_bar(position = "fill", stat="identity", width = 0.6, color = "black")+
  scale_y_continuous(labels = scales::percent)+ 
  brplt_theme +
  labs(
    title = "Patient Comorbidities by Surgery Type", 
    x = "Surgery Type",
    y = "Percentage of Patients",
    fill = "Disease"
  )
 dev.off()  
```

```{r}
# contingency table for gender
gender_counts <- xtabs(~ Female+`Type Surg` , data = hypoxia)

# convert counts to proportions within each surgery type
gender_prop <- prop.table(gender_counts, margin = 2)*100

# convert contingency table to df
gender_df <- as.data.frame(gender_prop)

# rename columns 
colnames(gender_df) <- c("Female", "TypeSurg", "Percent")

png("finalfig2.png", width = 1920, height = 1080, res = 300)
ggplot(gender_df, aes(x = TypeSurg, y = Percent, fill = Female)) +
  geom_col(position = position_dodge(width = 0.8), color = "black") +
  scale_fill_manual(values = c("steelblue", "lightpink"),
                    labels = c("Males", "Females"),
                    name = "Gender") +
  labs(
    title = "Gender Makeup for Each Type of Surgery",
    x = "Type of Surgery",
    y = "Percentage of Each Gender"
  ) + brplt_theme
dev.off()
# # barplot to show makeup of gender for each type of surgery
# barplot(gender_prop, col = c("steelblue", "lightpink"), beside = TRUE, main = "Count of Gender for Each Type of Surgery", xlab = "Type of Surgery", ylab = "Percentage of Each Gender")
# legend(
#   "topleft",
#   legend = c("Males", "Females"),
#   fill = c("steelblue", "lightpink")
# ) + brplt_theme

# contingency table for race
race_counts <- xtabs(~ Race+ `Type Surg` , data = hypoxia)

# convert counts to proportions within each surgery type
race_prop <- prop.table(race_counts, margin = 2)*100

# convert contingency table to df
race_df <- as.data.frame(race_prop)

# rename columns
colnames(race_df) <- c("Race", "TypeSurg", "Percent")

png("finalfig3.png", width = 1920, height = 1080, res = 300)
ggplot(race_df, aes(x = TypeSurg, y = Percent, fill = Race)) +
  geom_col(position = position_dodge(width = 0.9),color = "black") +
  scale_fill_manual(values = c("darkgreen", "lightgreen", "green"),
                    name = "Race", labels = c("African American","Caucasian", "Other")) +
  labs(
    title = "Race Makeup for Each Type of Surgery",
    x = "Type of Surgery",
    y = "Percentage of Each Race"
  ) + brplt_theme
dev.off()
# # bar plot to show makeup of race for each type of surgery
# barplot(race_prop, col = c("darkgreen", "lightgreen","green"), beside = TRUE, legend.text = c("African American", "Caucasian", "Other"), main = "Count of Race for Each Type of Surgery", xlab = "Type of Surgery", ylab = "Percentage of Each Race") + brplt_theme

# boxplot to compare duration of surgery between each type of surgery
boxplot(`Duration of Surg` ~ `Type Surg`, data = hypoxia, main = "Surgery Duration by Type", xlab = "Type of Surgery", ylab = "Duration of Surgery (hours)", col = c("lightblue", "steelblue","blue","darkblue"))
legend(
  "top",  
  horiz = TRUE,
  legend = c(1,2,3,4),       
  fill = c("lightblue", "steelblue", "blue", "darkblue"),
  title = "Type of Surgery"
) + bxplt_theme

```



```{r}
# bmi vs duration of surgery
hypoxia <- hypoxia %>%
  mutate(
    BMI_Category = case_when(
      BMI < 18.5 ~ "Underweight",
      BMI >= 18.5 & BMI < 25 ~ "Normal Weight",
      BMI >= 25 & BMI < 30 ~ "Overweight",
      BMI >= 30 & BMI < 35 ~ "Class 1 Obesity",
      BMI >= 35 & BMI < 40 ~ "Class 2 Obesity",
      BMI >= 40 ~ "Class 3 Obesity",
      TRUE ~ "UNKNOWN"
    )
  )
png("finalfig4.png", width = 1920, height = 1080, res = 300)
hypoxia$BMI_Category <- factor(hypoxia$BMI_Category,levels = c("Underweight", "Normal Weight", "Overweight","Class 1 Obesity", "Class 2 Obesity", "Class 3 Obesity"))
ggplot(hypoxia, aes(x = BMI_Category, y = `Duration of Surg`, fill = BMI_Category)) +
  geom_boxplot(color = "black") +
  scale_fill_brewer(palette = "Set2") +
  labs(
    title = "Comparing BMI vs Duration of Surgery",
    x = "BMI Category",
    y = "Duration of Surgery (hours)"
  ) +
  bxplt_theme
dev.off()
```





# Seble Plots
```{r}
# select the variables we care about
#in clude CPAP + AHI. well maybe not. AHI

data <- dplyr::select(hypoxia, 1:4,7:11,13:23, 25:34)

head(data)

# make a correlation plot

cor_matrix <- cor(data, use = "complete.obs")

test = cor.mtest(data)
```


```{r}
png("finalfig5.png", width = 2250, height = 1550, res = 300)
corrplot(cor_matrix,                                           
order = "FPC",                                            
p.mat = test$p,                                            
sig.level = c(0.001, 0.01, 0.05),                                   
insig = 'label_sig',                                    
pch.cex = 0.5,                                            
type = "upper",                                   
diag = FALSE,                                   
method="color")
dev.off()

```

```{r}
data$CPAP <- dplyr::recode(as.factor(data$CPAP), "0" = "No CPAP", "1" = "Use CPAP")

data$Smoking <-as.factor(data$Smoking)

data$Diabetes <-as.factor(data$Diabetes)

data$Hyper <-as.factor(data$Hyper)

data$CAD <-as.factor(data$CAD)

data$Phenylephrine <-dplyr::recode(as.factor(data$Phenylephrine), "0" = "No Phenylephrine", "1" = "Use Phenylephrine")


data$Epinephrine <-dplyr::recode(as.factor(data$Epinephrine), "0" = "No Epinephrine", "1" = "Use Epinephrine")

data$Female <-dplyr::recode(as.factor(data$Female), "0" = "Male", "1" = "Female")

data$Race <-dplyr::recode(as.factor(data$Race), "1" = "African American", "2" = "White", "3" = "Other")
```


```{r}
# comorbidities x Epinephrine graph version 3 - grouped prop graph comaring pos/neg for each comorbidity and epinephrine use. yay.

epi_com_counts_whole <- data %>%   
  dplyr::select(Epinephrine, Smoking, Diabetes, Hyper, CAD) %>%  
  gather(key = "Usage", value = "Diagnosis", -c(Epinephrine)) 

epi_com_prop_whole <- epi_com_counts_whole %>%  
group_by(Usage, Epinephrine, Diagnosis) %>% 
summarise(Frequency = n(), .groups = "drop") %>%  
group_by(Usage) %>%  
mutate(Proportion = Frequency / sum(Frequency)) 

epi_com_prop_whole

# grouped bar chart of comorbidities 
#tiff("epinephrine_stacked.tiff", width = 2500, height = 1500, res = 300)
epi_com_prop_whole$Epinephrine <-dplyr::recode(as.factor(epi_com_prop_whole$Epinephrine), "No Epinephrine"= "No Usage",  "Use Epinephrine" = "Usage")
png("finalfig6.png", width = 1920, height = 1350, res = 300)
ggplot(epi_com_prop_whole, aes(fill=Diagnosis, x=Epinephrine, y = Proportion)) + # might be better with stacked barplot? 
  geom_bar(position = "fill", stat="identity", width = 0.6, color = "black")+ scale_fill_brewer(palette = "Set2", name = "Diagnosis", labels = c("Not Present", "Present"))+
  scale_y_continuous(labels = scales::percent)+ facet_wrap(~Usage)+
  brplt_theme +
  labs(
    title = "Epinephrine Use in Surgery\n Across Patient Comorbidities", 
    x = "Epinephrine Use",
    y = "Percentage of Patients",
    fill = "Diagnosis"
  )
dev.off()
```

```{r}
# comorbidities x Phenylephrine graph version 3 was done - grouped prop graph comaring pos/neg for each comorbidity and epinephrine use. yay.
# basically no real difference this is consistent with correlation plot

ph_com_counts_whole <- data %>%   
  dplyr::select(Phenylephrine, Smoking, Diabetes, Hyper, CAD) %>%  
  gather(key = "Usage", value = "Diagnosis", -c(Phenylephrine)) 

ph_com_prop_whole <- ph_com_counts_whole %>%  
group_by(Usage, Phenylephrine, Diagnosis) %>% 
summarise(Frequency = n(), .groups = "drop") %>%  
group_by(Usage) %>%  
mutate(Proportion = Frequency / sum(Frequency))
```


```{r}
# grouped bar chart of comorbidities 
#tiff("phenylephrine_stacked.tiff", width = 2500, height = 1500, res = 300)
ph_com_prop_whole$Phenylephrine <-dplyr::recode(as.factor(ph_com_prop_whole$Phenylephrine), "No Phenylephrine"= "No Usage",  "Use Phenylephrine" = "Usage")

png("finalfig7.png", width = 1920, height = 1350, res = 300)
ggplot(ph_com_prop_whole, aes(fill=Diagnosis, x=Phenylephrine, y = Proportion)) + # might be better with stacked barplot? 
  geom_bar(position = "fill", stat="identity", width = 0.6, color = "black")+ scale_fill_brewer(palette = "Set2", name = "Diagnosis", labels = c("Not Present", "Present"))+ 
  scale_y_continuous(labels = scales::percent)+ facet_wrap(~Usage)+
  brplt_theme +
  labs(
    title = "Phenylephrine Use in Surgery\n Across Patient Comorbidities", 
    x = "Phenylephrine Use",
    y = "Percentage of Patients",
    fill = "Diagnosis"
  )
dev.off()
```

```{r}
# no instead we need cpap vs epi/phenyl use okay

cpap_com_counts_whole <- data %>%   
  dplyr::select(CPAP, Phenylephrine,Epinephrine) %>%  
  gather(key = "Usage", value = "Diagnosis", -c(CPAP)) 

cpap_com_prop_whole <- cpap_com_counts_whole %>%  
group_by(Usage, CPAP, Diagnosis) %>% 
summarise(Frequency = n(), .groups = "drop") %>%  
group_by(Usage) %>%  
mutate(Proportion = Frequency / sum(Frequency))
```


```{r}
cpap_com_prop_whole$Usage <- as.factor(cpap_com_prop_whole$Usage)
cpap_com_prop_whole$Diagnosis <- dplyr::recode(as.factor(cpap_com_prop_whole$Diagnosis),
                                               "No Epinephrine" = "No Usage", "Use Epinephrine" = "Usage",
                                               "No Phenylephrine" = "No Usage", "Use Phenylephrine" = "Usage")
cpap_com_prop_whole


# grouped bar chart of comorbidities 
#png("finalfig8.png", width = 1920, height = 1350, res = 300)
ggplot(cpap_com_prop_whole, aes(fill=CPAP, x=Diagnosis, y = Proportion)) + # might be better with stacked barplot? 
  facet_wrap(~Usage, nrow=2)+
  geom_bar(position = "fill", stat="identity", width = 0.6, color = "black")+ scale_fill_brewer(palette = "Set2", name = "Diagnosis", labels = c("No CPAP", "Use CPAP "))+ 
  scale_y_continuous(labels = scales::percent)+
  brplt_theme +
  labs(
    title = "Vascoconstrictors Across \n  CPAP Usage", 
    x = "Vasoconstrictor Use",
    y = "Percentage of Patients",
    fill = ""
  )
dev.off()

```


```{r}
# heart rate vs comobidities vers 2

hr_outcome <- hypoxia %>%   
  dplyr::select(`TWA HR`, Smoking, Diabetes, Hyper, CAD) %>%  
  gather(key = "Condition", value = "Diagnosis", -c(`TWA HR`))

hr_outcome$Diagnosis <- factor(hr_outcome$Diagnosis,levels = c(0,1))

#png("finalfig9.png", width = 1920, height = 1080, res = 300)
ggplot(hr_outcome, aes(x = Diagnosis, y = `TWA HR`, fill = Diagnosis)) +  
geom_boxplot()+bxplt_theme+ coord_flip() +
  scale_fill_brewer(palette = "Set2", direction = 1, labels = c("Not Present", "Present"))+
  labs(title = "Heart Rate During Surgery Across Comorbidities",
       x = "", y = "Surgical Heart Rate (beats/min)")+ 
  theme(
        legend.position = "top",
        strip.background = element_blank(),
        ) + facet_wrap(~Condition) 
dev.off()  
```


```{r}
# Dur vs BMI


p1<- ggplot(hypoxia, aes(x = `BMI`, y = `Duration of Surg`)) +  # Define data and aesthetics  
  geom_point(alpha = 0.6, size= 3, shape = 19, aes(color = BMI_Category)) +  
 theme_minimal(base_size = 12) +
  geom_smooth(method = "lm", se=FALSE)+  
  theme(
     plot.title = element_text(hjust = 0.5, face = "bold", size = 18),  # Centered, bold title    
    axis.text = element_text(size = 12, color = "black"), legend.position = "bottom",
     strip.background = element_rect(fill = "gray90", color = "black"),
    strip.text = element_text(size = 12, face = "bold"),
      panel.grid.major = element_line(color = "gray80", linetype = "dashed"), 
      panel.grid.minor = element_blank(),
    plot.caption = element_text(size=10, color="red", face="italic")
     
  )+scale_color_brewer(palette = "Set2")+
  labs(
    title = "Duration of Surgery vs BMI", 
    x = "BMI Score",
    y = "Duration of Surgery (hours)",
    caption = "BMI Categories based on CDC guidelines"
  )
#png("finalfig11.png", width = 1920, height = 1080, res = 300)
ggMarginal(p1, type="boxplot",groupColour = TRUE, groupFill = TRUE, size=7) 
dev.off() 

```





```{r}
# contingency table of comorbidities and type of surgery
outcome_counts <- hypoxia %>%   
  dplyr::select(`Type Surg`, Smoking, Diabetes, Hyper, CAD) %>%  
  gather(key = "Condition", value = "Diagnosis", -c(`Type Surg`))  %>%
  filter(Diagnosis == 1)
outcome_counts$`Type Surg` <- as.factor(outcome_counts$`Type Surg`)
outcome_counts$Condition   <- as.factor(outcome_counts$Condition)

condition_surg_table <- xtabs(~ `Type Surg` + Condition, data = outcome_counts)
condition_surg_table

kable(condition_surg_table, caption = "Type of Surgery by Comorbidity", row.names = T) %>%
  kable_styling(full_width = FALSE, bootstrap_options = c("striped", "hover"))
```

```{r}
# contingency table of comorbidities and epinephrine usage
epi_com_counts <- data %>%   
  dplyr::select(Epinephrine, Smoking, Diabetes, Hyper, CAD) %>%  
  gather(key = "Usage", value = "Diagnosis", -c(Epinephrine))  %>%
  filter(Diagnosis == 1)

epi_com_counts$Usage <- as.factor(epi_com_counts$Usage)
epi_com_counts$Epinephrine <- as.factor(epi_com_counts$Epinephrine)

condition_ep_table <- xtabs(~ Usage + Epinephrine, data = epi_com_counts)
condition_ep_table

kable(condition_ep_table, caption = "Epinephrine Usage for Comorbidities", row.names = T) %>%
  kable_styling(full_width = FALSE, bootstrap_options = c("striped", "hover"))
```

```{r}
# contingency table of comorbidities and phenylephrine usage

ph_com_counts <- data %>%   
  dplyr::select(Phenylephrine, Smoking, Diabetes, Hyper, CAD) %>%  
  gather(key = "Usage", value = "Diagnosis", -c(Phenylephrine)) %>%
  filter(Diagnosis == 1)

ph_com_counts$Usage <- as.factor(ph_com_counts$Usage)
ph_com_counts$Phenylephrine <- as.factor(ph_com_counts$Phenylephrine)

condition_ph_table <- xtabs(~ Usage + Phenylephrine, data = ph_com_counts)
condition_ph_table

kable(condition_ph_table, caption = "Phenylephrine Usage for Comorbidities", row.names = T) %>%
  kable_styling(full_width = FALSE, bootstrap_options = c("striped", "hover"))
```


```{r}
# summary table

data$AHI <- as.factor(data$AHI)

library(arsenal)

controls_report <- tableby.control(test=FALSE, total=FALSE,                                   
numeric.test="kwt", cat.test="chisq",                                   
numeric.stats=c("Nmiss", "median", "q1q3", "range"),                                   
cat.stats=c("Nmiss","countpct"),                                   
stats.labels=list(median="Median", q1q3="Q1,Q3", range = "Range"))

controls_report2 <- tableby.control(test=FALSE, total=FALSE,                                   
numeric.test="kwt", cat.test="chisq",                                   
numeric.stats=c("Nmiss", "median", "range"),                                   
cat.stats=c("Nmiss","countpct"),                                   
stats.labels=list(median="Median", range = "Range"))

#Create Labels
report_labels = c( `Duration of Surg` = "Duration of Surgery (hours)",                   
 Female = "Sex (0= male)",                          
 Race = "Race",                      
 BMI = "BMI Score",                       
`BMI Category` = "BMI Category",                       
Smoking =  "Smoking History",
Diabetes = "Diabetes History",
 CAD = "Coronary Heart Disease",
`TWA HR` = "Heart Rate During Surgery",
Epinephrine = "Use of Epinephrine",
Phenylephrine = "Use of Phenylephrine",
CPAP = "Use of CPAP"
)

report_1 <- tableby(`Type Surg`~ Female + Race + BMI + BMI_Category + `Duration of Surg` 
                    + Smoking +Diabetes + Hyper + CAD + `TWA HR` + Epinephrine + Phenylephrine + CPAP + AHI 
                      , data=hypoxia,
                    digits= 1, test= TRUE, digits.p=2, total = T, control=controls_report)

report_2 <- tableby(`Type Surg`~ Female + Race + BMI + `Duration of Surg` 
                    + Smoking +Diabetes + Hyper + CAD + `TWA HR` + Epinephrine + Phenylephrine + CPAP + AHI
                      , data=data,
                    digits= 1, test= TRUE, digits.p=2, total = T, control=controls_report2)

summary(report_2, test=TRUE, labelTranslations=report_labels, control=controls_report, title="Summary: Overall by Surgery Type", text = TRUE)
```


```{r}
# to export this change the inline output settings for R markdonw

#write2word(report_2,labelTranslations=report_labels,("hdv_final_summary"), quiet = FALSE) # to make this work remove the inline output setting
```


```{r}
# comorbidities x cpap graph version 3 was done - grouped prop graph comaring pos/neg for each comorbidity and epinephrine use. yay.
# basically no real difference this is consistent with correlation plot

cpap_counts <- hypoxia %>%   
  dplyr::select(AHI, CPAP) %>%  
  gather(key = "Label", value = "CPAP", -c(`AHI`))  

cpap_ahi_prop_whole <- cpap_counts %>%  
group_by(AHI, CPAP) %>% 
summarise(Frequency = n(), .groups = "drop") %>%  
group_by(CPAP) %>%  
mutate(Proportion = Frequency / sum(Frequency))

cpap_ahi_prop_whole
cpap_ahi_prop_whole$CPAP <- as.factor(cpap_ahi_prop_whole$CPAP)

# grouped bar chart of comorbidities 
#tiff("phenylephrine_stacked.tiff", width = 2500, height = 1500, res = 300)
png("finalfig10.png", width = 1920, height = 1080, res = 300)
ggplot(cpap_ahi_prop_whole, aes(fill=CPAP, x=AHI, y = Proportion)) + # might be better with stacked barplot? 
  geom_bar(position = "fill", stat="identity", width = 0.6, color = "black")+ 
    scale_fill_brewer(palette = "Set2", direction = 1, labels = c("No CPAP", "Use CPAP"))+
  scale_y_continuous(labels = scales::percent)+
  brplt_theme +
  labs(
    title = "CPAP Use in Surgery\n Across Sleep Apnea Index", 
    x = "Sleep Apnea Index (AHI)",
    y = "Percentage of Patients",
    fill = "CPAP Use"
  )
dev.off()
```









